services:
  redis:
    image: redis:latest
    container_name: redis-server-go
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    environment:
      REDIS_USER: "go"
      REDIS_PASSWORD: "og"

  mongodb:
    image: mongo:latest
    container_name: mongodb-server-go
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "go"
      MONGO_INITDB_ROOT_PASSWORD: "og"

volumes:
  redis-data:
  mongo-data:
